name: build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run unit tests
        run: ./gradlew clean build optimizedJar

  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Start local Blockchain
        run: docker-compose up -d

      - name: Run integration tests
        run: ./gradlew -Pscore-test.url=http://localhost:9082/api/v3 -Pscore-test.nid=0x3 -Pscore-test.keystoreName=./gochain-local/data/godWallet.json -Pscore-test.keystorePass=gochain -Pscore-test.tester.keystoreName=./gochain-local/data/godWallet.json -Pscore-test.tester.keystorePass=gochain integrationTest